# Generated by Django 4.0 on 2021-12-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
