# Generated by Django 4.0 on 2021-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(default='Body of this text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(default='Heading here', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
