# Generated by Django 4.0 on 2022-01-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_date_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='First name here', max_length=50)),
                ('lastname', models.CharField(default='Last name here', max_length=50)),
                ('email', models.EmailField(default='email address here', max_length=100)),
                ('passwd', models.CharField(default='Password here', max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
