# Generated by Django 4.0 on 2022-01-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
