# Generated by Django 4.0 on 2022-01-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_member_lastname_member_othernames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
