# Generated by Django 4.0 on 2022-01-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='First name here', max_length=50)),
                ('othernames', models.CharField(default='Other names here', max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(default='email address here', max_length=100)),
                ('passwd', models.CharField(default='Password here', max_length=50)),
            ],
        ),
    ]
